import { useDeferredValue, useMemo } from "react";
import { Search, BookOpen } from "lucide-react";
import { compendiumData } from "@/data/compendium";
import { compendiumRulesData } from "@/data/compendiumRules";
import { useLocalStorage } from "@/hooks/useLocalStorage";
import { createSingletonSlot } from "@/lib/singletonWidget";
import { SingletonGate } from "@/lib/SingletonGate";
import {
  validateNullableStringMax,
  validateStringMax,
  WIDGET_QUERY_MAX,
} from "@/lib/backup";

// Hand-curated DM summaries (compendiumData) plus bulk official/third-party
// rules text (compendiumRulesData, generated by generate-compendium.ts) —
// see that generator for how duplicate titles are avoided.
const allEntries = [...compendiumData, ...compendiumRulesData];
const categories = [...new Set(allEntries.map((e) => e.category))].sort();

// Precomputed lowercased title+content+tags per entry, built once at module
// load. A one-character query matches nearly all ~640 entries, and lowercasing
// every entry's full content on each keystroke was the whole per-key cost;
// mirrors the Wizard's Tome SPELL_SEARCH_INDEX.
const SEARCH_INDEX = new Map<(typeof allEntries)[number], string>(
  allEntries.map((e) => [e, `${e.title}\n${e.content}\n${e.tags.join(" ")}`.toLowerCase()]),
);

// Render caps — the result rows are not virtualized, so an uncapped broad match
// would stall the main thread (mirrors the Bestiary's MAX_RESULTS/preview).
const MAX_RESULTS = 200;
const UNFILTERED_PREVIEW = 7;

const COMPENDIUM_MOUNT_SLOT = createSingletonSlot();

// Compendium persists its query/category/selected-entry on shared keys, so a
// second live tile would clobber them — guard it as a singleton.
export function CompendiumWidget() {
  return (
    <SingletonGate
      slot={COMPENDIUM_MOUNT_SLOT}
      name="The Compendium"
      icon={<BookOpen className="w-6 h-6 text-amber-400/70" />}
    >
      <CompendiumBody />
    </SingletonGate>
  );
}

function CompendiumBody() {
  const [query, setQuery] = useLocalStorage<string>(
    "dm-compendium-query-v1",
    "",
    validateStringMax(WIDGET_QUERY_MAX),
  );
  const [selectedCategory, setSelectedCategory] = useLocalStorage<string>(
    "dm-compendium-category-v1",
    "All",
    validateStringMax(WIDGET_QUERY_MAX),
  );
  const [selectedEntry, setSelectedEntry] = useLocalStorage<string | null>(
    "dm-compendium-entry-v1",
    null,
    validateNullableStringMax(WIDGET_QUERY_MAX),
  );

  // The input stays driven by `query` (instant echo); the scan runs off the
  // deferred value so a broad match doesn't jank keystrokes (as in the Tome).
  const deferredQuery = useDeferredValue(query);
  const filtered = useMemo(() => {
    const q = deferredQuery.toLowerCase();
    return allEntries.filter((e) => {
      const matchesQuery = !q || (SEARCH_INDEX.get(e)?.includes(q) ?? false);
      const matchesCat = selectedCategory === "All" || e.category === selectedCategory;
      return matchesQuery && matchesCat;
    });
  }, [deferredQuery, selectedCategory]);

  const entry = selectedEntry ? allEntries.find((e) => e.id === selectedEntry) : null;
  // Derive `isFiltered` from `deferredQuery` (not the instant `query`) so the
  // cap and footer move in lockstep with `filtered` — otherwise the first
  // keystroke commits an urgent frame where isFiltered has flipped true but
  // `filtered` is still the empty-query set, flashing 200 unfiltered rows under
  // a "refine your search" footer until the deferred render catches up.
  const isFiltered = deferredQuery.trim() !== "" || selectedCategory !== "All";
  const cap = isFiltered ? MAX_RESULTS : UNFILTERED_PREVIEW;
  const visibleList = filtered.slice(0, cap);

  return (
    <div className="h-full min-h-0 flex flex-col">
      <div className="flex items-center gap-2 mb-2">
        <div className="relative flex-1">
          <Search className="absolute left-2 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-purple-400" />
          <input
            type="text"
            value={query}
            onChange={(e) => { setQuery(e.target.value); setSelectedEntry(null); }}
            placeholder="Search 5.5e rules…"
            className="w-full pl-7 pr-2 py-1 bg-gray-900 border border-purple-800/50 rounded text-xs text-gray-200 placeholder-gray-500 focus:outline-none focus:border-purple-500"
          />
        </div>
        <select
          value={selectedCategory}
          onChange={(e) => { setSelectedCategory(e.target.value); setSelectedEntry(null); }}
          className="text-xs bg-gray-900 border border-purple-800/50 rounded px-2 py-1 text-gray-300 focus:outline-none focus:border-purple-500"
        >
          <option>All</option>
          {categories.map((c) => (
            <option key={c}>{c}</option>
          ))}
        </select>
      </div>

      {entry ? (
        <div className="flex-1 min-h-0 overflow-y-auto">
          <button
            onClick={() => setSelectedEntry(null)}
            className="text-xs text-purple-400 hover:text-purple-300 mb-2 flex items-center gap-1"
          >
            ← Back to results
          </button>
          <div className="bg-gray-900/80 border border-purple-700/40 rounded p-3">
            <div className="flex items-start justify-between gap-2 mb-2">
              <h3 className="text-sm font-bold text-white">{entry.title}</h3>
              <span className="text-xs text-purple-400 bg-purple-900/40 px-2 py-0.5 rounded-full shrink-0">
                {entry.category}
              </span>
            </div>
            <p className="text-xs text-gray-300 leading-relaxed whitespace-pre-line">{entry.content}</p>
            <div className="flex flex-wrap gap-1 mt-3">
              {entry.tags.map((tag) => (
                <span key={tag} className="text-xs text-gray-500 bg-gray-800 px-1.5 py-0.5 rounded">
                  {tag}
                </span>
              ))}
            </div>
          </div>
        </div>
      ) : (
        <div className="flex-1 min-h-0 overflow-y-auto space-y-1">
          {filtered.length === 0 && (
            <div className="text-center py-4 text-gray-500 text-xs flex flex-col items-center gap-2">
              <BookOpen className="w-6 h-6 opacity-30" />
              No entries found
            </div>
          )}
          {visibleList.map((e) => (
            <button
              key={e.id}
              onClick={() => setSelectedEntry(e.id)}
              className="w-full text-left px-2 py-1.5 bg-gray-900/60 hover:bg-purple-900/30 border border-purple-900/30 hover:border-purple-600/50 rounded transition-all group"
            >
              <div className="flex items-center justify-between">
                <span className="text-xs font-medium text-gray-200 group-hover:text-white transition-colors">
                  {e.title}
                </span>
                <span className="text-xs text-purple-500 shrink-0">{e.category}</span>
              </div>
            </button>
          ))}
          {!isFiltered && filtered.length > UNFILTERED_PREVIEW && (
            <div className="text-center py-2 text-[10px] text-gray-600">
              Showing {UNFILTERED_PREVIEW} of {filtered.length} — search to filter
            </div>
          )}
          {isFiltered && filtered.length > MAX_RESULTS && (
            <div className="text-center py-2 text-[10px] text-gray-600">
              Showing first {MAX_RESULTS} of {filtered.length.toLocaleString()} — refine your search
            </div>
          )}
        </div>
      )}
    </div>
  );
}
